version: "3"
services:
  web:
    build: .
    command: bundle exec bin/rails server -b 0.0.0.0 -p 3030
    # command: unset PORT && env RUBY_DEBUG_OPEN=true bundle exec bin/rails server -b 0.0.0.0 -p 3030
    volumes:
      - .:/app
    ports:
      - "3030:3030"
      - "1234:1234"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  css:
    build: .
    command: yarn watch:css
    volumes:
      - .:/app
    ports:
      - "3035:3035"
    environment:
      - "NODE_ENV=production"
      - "RAILS_ENV=production"
    env_file:
      - .env

  js:
    build: .
    command: env yarn build --watch
    volumes:
      - .:/app
    ports:
      - "3036:3036"
    environment:
      - "NODE_ENV=production"
      - "RAILS_ENV=production"
    env_file:
      - .env

  redis:
    image: "redis:7.4-alpine"
    command: redis-server
    ports:
      - "6380:6379"
    volumes:
      - "redis:/data"
    # expose:
    #   - "6380:6379"


  mailhog:
      image: mailhog/mailhog
      container_name: 'mailhog'
      ports:
        - "1025:1025"
        - "8025:8025"


volumes:
  pg_data:
  redis:
